language: node_js
node_js: "6"

sudo: required
dist: trusty

addons:
    apt:
        sources:
            - google-chrome

cache:
    directories:
        - $HOME/.cache/yarn

before_install:
  - sudo apt-get install -y --allow-unauthenticated google-chrome-stable

script:
    - npm run test
    - npm run build
